name: SocialCreditsPlugin
version: '${project.version}'
main: me.necroliner.socialcreditsplugin.SocialCreditSystem
api-version: 1.18
authors: [ Necroliner ]
description: Plugin implementing a social credits based system in minecraft
commands:
  scs:
    description: displays social credits count
    usage: /<command>
